const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8000/inspection-workspace.html');
 await p.evaluate(()=>localStorage.setItem('apex_inspection_record_v1',JSON.stringify({id:'test',photos:{'Ridge:Ridge Closeup':{section:'Ridge',label:'Ridge Closeup',originalKey:'unchanged',storageStatus:'stored'}},observations:{old:{id:'old',section:'Ridge',details:'Existing ridge note',photoId:'Ridge:Ridge Closeup',updatedAt:new Date().toISOString()}},absences:{},notes:{},sectionStates:{}})));
 await p.reload();await p.locator('#fieldSections').waitFor();
 const card=p.locator('.field-section-card').filter({has:p.getByRole('heading',{name:'Shingles'})});
 await card.locator('summary').click();
 assert.match(await card.innerText(),/1 photos · 1 notes/);
 assert.match(await card.innerText(),/Ridge Closeup\s+Captured/);
 await card.getByRole('link',{name:/Brittle test/}).click();
 await p.locator('#brittleForm').waitFor();
 await p.locator('#brittleForm [name=location]').fill('Front slope');
 await p.locator('#brittleForm [name=result]').selectOption({label:'Not performed'});
 await p.locator('#brittleForm [name=details]').fill('Cold shingles; deferred to qualified roofer.');
 await p.getByRole('button',{name:'Save test observation'}).click();
 assert.match(await p.locator('#brittleStatus').innerText(),/Saved/);
 await p.getByRole('button',{name:'Save test observation'}).click();
 const record=await p.evaluate(()=>InspectionStore.get());
 assert.equal(Object.keys(record.observations).length,2);
 assert.equal(record.photos['Ridge:Ridge Closeup'].originalKey,'unchanged');
 assert.equal(record.observations.old.section,'Shingles');
 assert.equal(Object.values(record.observations).find(n=>n.brittleTest).brittleTest.result,'Not performed');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.goto('http://127.0.0.1:8000/inspection-review.html');
 await p.locator('#reviewContent').waitFor();
 assert.match(await p.locator('#reviewContent').innerText(),/Brittle test — Not performed/);
 assert.equal(await p.locator('.review-missing').filter({hasText:'Brittle test'}).count(),0);
 await p.goto('http://127.0.0.1:8000/ridge-inspection.html?item=2');
 await p.waitForURL('**/brittle-test.html');
 assert.deepEqual(errors,[]);
 console.log('PASS: Shingles migration, mobile brittle test, save/report and navigation');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
