const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8000/inspection-workspace.html');
 await p.evaluate(()=>localStorage.setItem('apex_inspection_record_v1',JSON.stringify({id:'test',photos:{'Ridge:Ridge Closeup':{section:'Ridge',label:'Ridge Closeup',originalKey:'unchanged',storageStatus:'stored'}},observations:{old:{id:'old',section:'Ridge',details:'Existing ridge note',photoId:'Ridge:Ridge Closeup',updatedAt:new Date().toISOString()}},absences:{},notes:{},sectionStates:{}})));
 await p.reload();await p.locator('#fieldSections').waitFor();
 const card=p.locator('.field-section-card').filter({has:p.getByRole('heading',{name:'Shingles'})});
 await card.locator('summary').click();
 assert.match(await card.innerText(),/1 photos · 1 notes/);
 assert.match(await card.innerText(),/Ridge Closeup\s+Captured/);
 await card.getByRole('link',{name:/Brittle test/}).click();
 await p.locator('#brittleCapture #fieldNoteForm').waitFor();
 assert.equal(await p.locator('#brittleForm').count(),0);
 assert.equal(await p.locator('#fieldEditDetails').getAttribute('open'),null);
 assert.ok(await p.getByRole('button',{name:'Take before photo',exact:true}).isVisible());
 assert.ok(await p.getByRole('button',{name:'Take after photo',exact:true}).isVisible());
 const data=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=50;c.height=50;return c.toDataURL();});
 for(const phase of ['before','after']) {
  const chooser=p.waitForEvent('filechooser');await p.getByRole('button',{name:`Upload ${phase} photo`,exact:true}).click();
  await (await chooser).setFiles({name:`${phase}.png`,mimeType:'image/png',buffer:Buffer.from(data.split(',')[1],'base64')});
  await p.locator(`[data-phase-photos="${phase}"] img`).waitFor();
 }
 await p.reload();
 await p.locator('[data-phase-photos="before"] img').waitFor();
 await p.locator('[data-phase-photos="after"] img').waitFor();
 await p.locator('#fieldPhotoPreview').waitFor({state:'visible'});
 await p.locator('[name=details]').fill('Front slope. Brittle test not performed; cold shingles.');
 await p.evaluate(()=>{ObservationExtraction.extract=async(text,components,section,photo)=>{if(!photo)throw Error('Missing test photo');return {fields:{location:'Front slope'},review:{status:'unable_to_assess',summary:'A still photo does not establish flexibility.',checks:[]}};};});
 await p.locator('#fieldFill').click();
 await p.waitForFunction(()=>document.getElementById('fieldFillStatus').textContent.startsWith('Note prepared'));
 assert.equal(await p.locator('[name=location]').inputValue(),'Front slope');
 await p.locator('#fieldNoteForm [type=submit]').click();
 assert.match(await p.locator('#fieldSaveStatus').innerText(),/Added to report/);
 await p.locator('#fieldNoteForm [type=submit]').click();
 const record=await p.evaluate(()=>InspectionStore.get());
 assert.equal(Object.keys(record.observations).length,2);
 assert.equal(record.photos['Ridge:Ridge Closeup'].originalKey,'unchanged');
 assert.equal(record.observations.old.section,'Shingles');
 const note=Object.values(record.observations).find(n=>n.brittleTest);
 assert.equal(note.brittleTest.method,'photo-and-dictation');
 assert.ok(note.photoId);
 assert.equal(note.brittleTest.photos.before.length,1);assert.equal(note.brittleTest.photos.after.length,1);
 assert.notEqual(note.brittleTest.photos.before[0],note.brittleTest.photos.after[0]);
 assert.match(record.photos[note.brittleTest.photos.before[0]].label,/Before test/);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.goto('http://127.0.0.1:8000/inspection-review.html');
 await p.locator('#reviewContent').waitFor();
 assert.match(await p.locator('#reviewContent').innerText(),/Brittle test not performed/);
 assert.ok(await p.getByRole('button',{name:'Before test photo',exact:true}).isVisible());
 assert.ok(await p.getByRole('button',{name:'After test photo',exact:true}).isVisible());
 assert.equal(await p.locator('.review-missing').filter({hasText:'Brittle test'}).count(),0);
 await p.goto('http://127.0.0.1:8000/ridge-inspection.html?item=2');
 await p.waitForURL('**/brittle-test.html');
 assert.deepEqual(errors,[]);
 console.log('PASS: Shingles migration, mobile brittle test, save/report and navigation');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
